version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - PGHOST=db
      - PGDATABASE=forms
      - PGUSERNAME=forms
      - PGPASSWORD=forms
      - NODE_ENV=production
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped
  db:
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=forms
      - POSTGRES_PASSWORD=forms
      - POSTGRES_DB=forms
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U forms']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - app-network
    restart: unless-stopped
    command: postgres -c shared_buffers=256MB -c max_connections=100

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    name: dynamic-form-builder-postgres-data
